name: keras_venv
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip=21.2.4
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - cudnn
  - cpuonly
  - pip:
    - tensorflow
    - gym
