name: keras_venv
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip=21.2.4
  - cudatoolkit=11.3
  - cudnn
  - pip:
    - tensorflow
    - gym
    - kaggle-environments>=0.1.6
    - tqdm
